#!/usr/bin/env python3
"""Generate MP3 audio for every Chinese text in the app with Microsoft Edge neural voices.

Usage:
    pip install edge-tts
    node tools/collect_texts.js > audio_texts.json
    python tools/gen_audio.py audio_texts.json

Writes audio/<hash>.mp3 files and audio/manifest.js (window.CB_AUDIO = {"F|文本": "hash.mp3"}).
Existing files are skipped, so re-runs only generate new or changed sentences.
edge-tts is an unofficial client of Microsoft's online voice service; if it stops working,
swap `synth()` for another TTS provider — the manifest format stays the same.
"""
import asyncio, hashlib, json, os, sys

VOICES = {"F": "zh-CN-XiaoxiaoNeural", "M": "zh-CN-YunxiNeural"}
RATE = "-10%"            # slightly slower for learners
CONCURRENCY = 6
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO_DIR = os.path.join(ROOT, "audio")


def fname(v, t):
    return hashlib.sha1(f"{VOICES[v]}|{RATE}|{t}".encode("utf-8")).hexdigest()[:14] + ".mp3"


async def synth(v, t, path):
    import edge_tts
    await edge_tts.Communicate(t, VOICES[v], rate=RATE).save(path)


async def worker(sem, item, stats):
    v, t = item["v"], item["t"]
    path = os.path.join(AUDIO_DIR, fname(v, t))
    if os.path.exists(path) and os.path.getsize(path) > 0:
        stats["skipped"] += 1
        return
    async with sem:
        for attempt in range(4):
            try:
                await synth(v, t, path + ".part")
                os.replace(path + ".part", path)
                stats["made"] += 1
                return
            except Exception as e:  # network hiccups / rate limits
                await asyncio.sleep(2 * (attempt + 1))
                last = e
        stats["failed"].append((v, t, str(last)))
        if os.path.exists(path + ".part"):
            os.remove(path + ".part")


async def main(src):
    items = json.load(open(src, encoding="utf-8"))
    os.makedirs(AUDIO_DIR, exist_ok=True)
    stats = {"made": 0, "skipped": 0, "failed": []}
    sem = asyncio.Semaphore(CONCURRENCY)
    await asyncio.gather(*(worker(sem, it, stats) for it in items))

    manifest = {}
    for it in items:
        f = fname(it["v"], it["t"])
        if os.path.exists(os.path.join(AUDIO_DIR, f)):
            manifest[f'{it["v"]}|{it["t"]}'] = f
    with open(os.path.join(AUDIO_DIR, "manifest.js"), "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/gen_audio.py — do not edit. */\n")
        fh.write("window.CB_AUDIO = " + json.dumps(manifest, ensure_ascii=False, separators=(",", ":")) + ";\n")

    print(f"texts: {len(items)}  generated: {stats['made']}  cached: {stats['skipped']}  "
          f"failed: {len(stats['failed'])}  in manifest: {len(manifest)}")
    for v, t, e in stats["failed"][:10]:
        print(f"  FAILED [{v}] {t[:30]}… {e[:80]}")
    # Deploy anyway with partial audio, but fail loudly if most of it is missing.
    if len(manifest) < 0.9 * len(items):
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main(sys.argv[1] if len(sys.argv) > 1 else "audio_texts.json"))
