#!/usr/bin/env python3
"""Generate MP3 audio for every Chinese text in the app with Microsoft Edge neural voices.

Usage:
    pip install edge-tts
    node tools/collect_texts.js > audio_texts.json
    python tools/gen_audio.py audio_texts.json

Writes audio/<hash>.mp3 files and audio/manifest.js (window.CB_AUDIO = {"F|文本": "hash.mp3"}).
Existing files are skipped, so re-runs only generate new or changed sentences.
edge-tts is an unofficial client of Microsoft's online voice service; if it stops working,
swap `synth()` for another TTS provider — the manifest format stays the same.
"""
import asyncio, hashlib, json, os, sys

VOICES = {"F": "zh-CN-XiaoxiaoNeural", "M": "zh-CN-YunxiNeural"}
RATE = "-10%"            # slightly slower for learners
CONCURRENCY = 6
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO_DIR = os.path.join(ROOT, "audio")


def fname(v, t):
    return hashlib.sha1(f"{VOICES[v]}|{RATE}|{t}".encode("utf-8")).hexdigest()[:14] + ".mp3"


async def synth(v, t, path):
    import edge_tts
    await edge_tts.Communicate(t, VOICES[v], rate=RATE).save(path)


async def worker(sem, item, stats):
    v, t = item["v"], item["t"]
    path = os.path.join(AUDIO_DIR, fname(v, t))
    if os.path.exists(path) and os.path.getsize(path) > 0:
        stats["skipped"] += 1
        return
    async with sem:
        for attempt in range(4):
            try:
                await synth(v, t, path + ".part")
                os.replace(path + ".part", path)
                stats["made"] += 1
                return
            except Exception as e:  # network hiccups / rate limits
                await asyncio.sleep(2 * (attempt + 1))
                last = e
        stats["failed"].append((v, t, str(last)))
        if os.path.exists(path + ".part"):
            os.remove(path + ".part")


SHRUNK = os.path.join(AUDIO_DIR, ".shrunk")   # files already re-encoded (never re-encode twice)
SHRINK_ARGS = ["-ac", "1", "-ar", "24000", "-b:a", "32k"]


def shrink_all(files):
    """Re-encode each clip once to 32 kbps mono MP3 (~1/3 smaller than edge-tts' 48 kbps).
    Speech stays clear at this rate, and MP3 plays everywhere, including iPhone. Skipped if ffmpeg is missing."""
    import shutil, subprocess
    from concurrent.futures import ThreadPoolExecutor
    ff = shutil.which("ffmpeg") or os.environ.get("FFMPEG")
    if not ff:
        print("ffmpeg not found — keeping original audio size")
        return
    done = set(open(SHRUNK).read().split()) if os.path.exists(SHRUNK) else set()
    todo = [f for f in files if f not in done]
    saved = [0]

    def one(f):
        src = os.path.join(AUDIO_DIR, f); tmp = src + ".tmp.mp3"
        r = subprocess.run([ff, "-v", "error", "-y", "-i", src, *SHRINK_ARGS, tmp], capture_output=True)
        if r.returncode == 0 and os.path.exists(tmp) and 0 < os.path.getsize(tmp) < os.path.getsize(src):
            saved[0] += os.path.getsize(src) - os.path.getsize(tmp)
            os.replace(tmp, src)
        elif os.path.exists(tmp):
            os.remove(tmp)
        return f

    try:
        with ThreadPoolExecutor(max_workers=8) as ex:
            for f in ex.map(one, todo):
                done.add(f)
    finally:  # record progress even if interrupted, so no clip is ever re-encoded twice
        with open(SHRUNK, "w") as fh:
            fh.write("\n".join(sorted(done)))
    print(f"re-encoded {len(todo)} clips, saved {saved[0] / 1048576:.1f} MB")


async def main(src):
    items = json.load(open(src, encoding="utf-8"))
    os.makedirs(AUDIO_DIR, exist_ok=True)
    stats = {"made": 0, "skipped": 0, "failed": []}
    sem = asyncio.Semaphore(CONCURRENCY)
    await asyncio.gather(*(worker(sem, it, stats) for it in items))

    manifest = {}
    for it in items:
        f = fname(it["v"], it["t"])
        if os.path.exists(os.path.join(AUDIO_DIR, f)):
            manifest[f'{it["v"]}|{it["t"]}'] = f
    shrink_all(sorted(set(manifest.values())))
    with open(os.path.join(AUDIO_DIR, "manifest.js"), "w", encoding="utf-8") as fh:
        fh.write("/* Generated by tools/gen_audio.py — do not edit. */\n")
        fh.write("window.CB_AUDIO = " + json.dumps(manifest, ensure_ascii=False, separators=(",", ":")) + ";\n")

    print(f"texts: {len(items)}  generated: {stats['made']}  cached: {stats['skipped']}  "
          f"failed: {len(stats['failed'])}  in manifest: {len(manifest)}")
    for v, t, e in stats["failed"][:10]:
        print(f"  FAILED [{v}] {t[:30]}… {e[:80]}")
    # Deploy anyway with partial audio, but fail loudly if most of it is missing.
    if len(manifest) < 0.9 * len(items):
        sys.exit(1)


if __name__ == "__main__":
    asyncio.run(main(sys.argv[1] if len(sys.argv) > 1 else "audio_texts.json"))
