# Extra readings for the HSK 5 generator (exec'd by build_hsk5.py): word tokens whose CEDICT reading is
# missing, ambiguous or lacks the neutral tone normally used in the lessons. Syllables separated by spaces.
WORD.update({
    "孙子": "sūn zi", "妻子": "qī zi", "同一": "tóng yī",
    "星星": "xīng xing",
    "问问": "wèn wen", "尝尝": "cháng chang", "谈谈": "tán tan", "看看": "kàn kan", "想想": "xiǎng xiang", "试试": "shì shi",
    "听听": "tīng ting", "说说": "shuō shuo", "找找": "zhǎo zhao", "聊聊": "liáo liao", "猜猜": "cāi cai", "毕业生": "bì yè shēng",
    "东西": "dōng xi", "告诉": "gào su", "结果": "jié guǒ", "便宜": "pián yi", "地方": "dì fang", "生意": "shēng yi",
    "爸爸": "bà ba", "妈妈": "mā ma", "哥哥": "gē ge", "姐姐": "jiě jie", "弟弟": "dì di", "妹妹": "mèi mei",
    "爷爷": "yé ye", "奶奶": "nǎi nai", "事情": "shì qing", "关系": "guān xi", "认识": "rèn shi", "先生": "xiān sheng",
    "漂亮": "piào liang", "明白": "míng bai", "舒服": "shū fu", "窗户": "chuāng hu", "休息": "xiū xi", "麻烦": "má fan",
    "打算": "dǎ suan", "聪明": "cōng ming", "热闹": "rè nao", "客气": "kè qi", "力气": "lì qi", "脾气": "pí qi",
    "眼睛": "yǎn jing", "耳朵": "ěr duo", "头发": "tóu fa", "月亮": "yuè liang", "觉得": "jué de", "记得": "jì de",
    "多少": "duō shao", "部分": "bù fen", "师傅": "shī fu", "大夫": "dài fu", "丈夫": "zhàng fu", "衣服": "yī fu",
    "知道": "zhī dào", "时候": "shí hou", "朋友": "péng you", "喜欢": "xǐ huan", "清楚": "qīng chu", "意思": "yì si",
    "消息": "xiāo xi", "困难": "kùn nan", "商量": "shāng liang", "厉害": "lì hai", "护士": "hù shi", "学生": "xué sheng",
    "谢谢": "xiè xie", "任务": "rèn wu", "合同": "hé tong", "收拾": "shōu shi", "暖和": "nuǎn huo", "凉快": "liáng kuai",
    "钥匙": "yào shi", "玻璃": "bō li", "萝卜": "luó bo", "葡萄": "pú tao", "行李": "xíng li", "故事": "gù shi",
    "名字": "míng zi", "笑话": "xiào hua", "精神": "jīng shen", "亲戚": "qīn qi", "队伍": "duì wu", "比方": "bǐ fang",
    "怎么": "zěn me", "什么": "shén me", "这么": "zhè me", "那么": "nà me", "为什么": "wèi shén me", "我们": "wǒ men",
    "你们": "nǐ men", "他们": "tā men", "她们": "tā men", "咱们": "zán men", "人们": "rén men", "这个": "zhè ge",
    "那个": "nà ge", "这里": "zhè lǐ", "那里": "nà lǐ", "哪里": "nǎ lǐ", "这儿": "zhè r", "那儿": "nà r", "哪儿": "nǎ r",
    "一点儿": "yī diǎn r", "有点儿": "yǒu diǎn r", "一会儿": "yī huì r", "一下": "yī xià", "一些": "yī xiē",
    "没有": "méi yǒu", "还是": "hái shi", "还有": "hái yǒu", "只有": "zhǐ yǒu", "只要": "zhǐ yào", "只是": "zhǐ shì",
    "只好": "zhǐ hǎo", "得到": "dé dào", "觉": "jué", "睡觉": "shuì jiào", "音乐": "yīn yuè", "快乐": "kuài lè",
    "银行": "yín háng", "行业": "háng yè", "重要": "zhòng yào", "重新": "chóng xīn", "长大": "zhǎng dà",
    "校长": "xiào zhǎng", "成长": "chéng zhǎng", "生长": "shēng zhǎng", "教室": "jiào shì", "教育": "jiào yù",
    "教授": "jiào shòu", "教练": "jiào liàn", "教训": "jiào xun", "当时": "dāng shí", "当然": "dāng rán",
    "适当": "shì dàng", "空气": "kōng qì", "空调": "kōng tiáo", "空儿": "kòng r", "有空": "yǒu kòng",
    "干净": "gān jìng", "干杯": "gān bēi", "能干": "néng gàn", "因为": "yīn wèi", "为了": "wèi le",
    "认为": "rèn wéi", "以为": "yǐ wéi", "成为": "chéng wéi", "作为": "zuò wéi", "行为": "xíng wéi",
    "还": "hái", "应该": "yīng gāi", "答应": "dā ying", "适应": "shì yìng", "反应": "fǎn yìng", "应聘": "yìng pìn",
    "应付": "yìng fu", "应用": "yìng yòng", "差不多": "chà bu duō", "出差": "chū chāi", "差别": "chā bié",
    "差距": "chā jù", "数字": "shù zì", "数量": "shù liàng", "数学": "shù xué", "数据": "shù jù", "多数": "duō shù",
    "调查": "diào chá", "调整": "tiáo zhěng", "强调": "qiáng diào", "兴趣": "xìng qù", "高兴": "gāo xìng",
    "兴奋": "xīng fèn", "处理": "chǔ lǐ", "好处": "hǎo chu", "到处": "dào chù", "相处": "xiāng chǔ",
    "相信": "xiāng xìn", "照相": "zhào xiàng", "相机": "xiàng jī", "种类": "zhǒng lèi", "种": "zhǒng",
    "假期": "jià qī", "放假": "fàng jià", "请假": "qǐng jià", "假如": "jiǎ rú", "暑假": "shǔ jià", "寒假": "hán jià",
    "看见": "kàn jiàn", "听见": "tīng jiàn", "觉得": "jué de", "舍不得": "shě bu de", "来不及": "lái bu jí",
    "对不起": "duì bu qǐ", "了不起": "liǎo bu qǐ", "受不了": "shòu bu liǎo", "怪不得": "guài bu de",
    "朝": "cháo", "地上": "dì shang", "晚上": "wǎn shang", "早上": "zǎo shang", "身上": "shēn shang",
    "一一": "yī yī", "第一": "dì yī", "爱好": "ài hào", "好奇": "hào qí", "好客": "hào kè", "背后": "bèi hòu",
    "似的": "shì de", "似乎": "sì hū", "的话": "de huà", "目的": "mù dì", "的确": "dí què", "要求": "yāo qiú",
    "重": "zhòng", "倒": "dào", "倒是": "dào shì", "中间": "zhōng jiān", "房间": "fáng jiān", "时间": "shí jiān",
    "大家": "dà jiā", "出来": "chū lái", "回来": "huí lái", "进来": "jìn lái", "过来": "guò lái", "起来": "qǐ lái",
    "下来": "xià lái", "上来": "shàng lái", "出去": "chū qù", "回去": "huí qù", "过去": "guò qù", "下去": "xià qù",
    "上去": "shàng qù", "进去": "jìn qù",
})
HEAD.update({})
